// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// max_tail_prob
NumericVector max_tail_prob(NumericMatrix dbinom1, NumericMatrix dbinom2, IntegerVector x1, IntegerVector x2, IntegerVector idx_last, IntegerVector g_lo, IntegerVector g_hi);
RcppExport SEXP _bbssr_max_tail_prob(SEXP dbinom1SEXP, SEXP dbinom2SEXP, SEXP x1SEXP, SEXP x2SEXP, SEXP idx_lastSEXP, SEXP g_loSEXP, SEXP g_hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dbinom1(dbinom1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dbinom2(dbinom2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx_last(idx_lastSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g_lo(g_loSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g_hi(g_hiSEXP);
    rcpp_result_gen = Rcpp::wrap(max_tail_prob(dbinom1, dbinom2, x1, x2, idx_last, g_lo, g_hi));
    return rcpp_result_gen;
END_RCPP
}
// power_from_rr
double power_from_rr(LogicalMatrix RR, NumericVector dbinom1, NumericVector dbinom2);
RcppExport SEXP _bbssr_power_from_rr(SEXP RRSEXP, SEXP dbinom1SEXP, SEXP dbinom2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dbinom1(dbinom1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dbinom2(dbinom2SEXP);
    rcpp_result_gen = Rcpp::wrap(power_from_rr(RR, dbinom1, dbinom2));
    return rcpp_result_gen;
END_RCPP
}
// bernstein_max
List bernstein_max(NumericVector coef, double tol, int max_pieces);
RcppExport SEXP _bbssr_bernstein_max(SEXP coefSEXP, SEXP tolSEXP, SEXP max_piecesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_pieces(max_piecesSEXP);
    rcpp_result_gen = Rcpp::wrap(bernstein_max(coef, tol, max_pieces));
    return rcpp_result_gen;
END_RCPP
}
// binom_conv_matrix
NumericMatrix binom_conv_matrix(int N, double a, double c);
RcppExport SEXP _bbssr_binom_conv_matrix(SEXP NSEXP, SEXP aSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(binom_conv_matrix(N, a, c));
    return rcpp_result_gen;
END_RCPP
}
// bssr_cond_reject
List bssr_cond_reject(List rr_list, IntegerVector rr_id, IntegerVector n21, IntegerVector n22, int n11, int n12);
RcppExport SEXP _bbssr_bssr_cond_reject(SEXP rr_listSEXP, SEXP rr_idSEXP, SEXP n21SEXP, SEXP n22SEXP, SEXP n11SEXP, SEXP n12SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rr_list(rr_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rr_id(rr_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n21(n21SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n22(n22SEXP);
    Rcpp::traits::input_parameter< int >::type n11(n11SEXP);
    Rcpp::traits::input_parameter< int >::type n12(n12SEXP);
    rcpp_result_gen = Rcpp::wrap(bssr_cond_reject(rr_list, rr_id, n21, n22, n11, n12));
    return rcpp_result_gen;
END_RCPP
}
// bssr_power
NumericVector bssr_power(List rr_list, IntegerVector rr_id, IntegerVector x11, IntegerVector x12, IntegerVector n21, IntegerVector n22, NumericVector p1, NumericVector p2, int n11, int n12);
RcppExport SEXP _bbssr_bssr_power(SEXP rr_listSEXP, SEXP rr_idSEXP, SEXP x11SEXP, SEXP x12SEXP, SEXP n21SEXP, SEXP n22SEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP n11SEXP, SEXP n12SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rr_list(rr_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rr_id(rr_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x11(x11SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x12(x12SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n21(n21SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n22(n22SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< int >::type n11(n11SEXP);
    Rcpp::traits::input_parameter< int >::type n12(n12SEXP);
    rcpp_result_gen = Rcpp::wrap(bssr_power(rr_list, rr_id, x11, x12, n21, n22, p1, p2, n11, n12));
    return rcpp_result_gen;
END_RCPP
}
// max_tail_prob_refined
NumericVector max_tail_prob_refined(NumericMatrix dbinom1, NumericMatrix dbinom2, IntegerVector x1, IntegerVector x2, IntegerVector idx_last, IntegerVector g_lo, IntegerVector g_hi, NumericVector theta);
RcppExport SEXP _bbssr_max_tail_prob_refined(SEXP dbinom1SEXP, SEXP dbinom2SEXP, SEXP x1SEXP, SEXP x2SEXP, SEXP idx_lastSEXP, SEXP g_loSEXP, SEXP g_hiSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dbinom1(dbinom1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dbinom2(dbinom2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx_last(idx_lastSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g_lo(g_loSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g_hi(g_hiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(max_tail_prob_refined(dbinom1, dbinom2, x1, x2, idx_last, g_lo, g_hi, theta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bbssr_max_tail_prob", (DL_FUNC) &_bbssr_max_tail_prob, 7},
    {"_bbssr_power_from_rr", (DL_FUNC) &_bbssr_power_from_rr, 3},
    {"_bbssr_bernstein_max", (DL_FUNC) &_bbssr_bernstein_max, 3},
    {"_bbssr_binom_conv_matrix", (DL_FUNC) &_bbssr_binom_conv_matrix, 3},
    {"_bbssr_bssr_cond_reject", (DL_FUNC) &_bbssr_bssr_cond_reject, 6},
    {"_bbssr_bssr_power", (DL_FUNC) &_bbssr_bssr_power, 10},
    {"_bbssr_max_tail_prob_refined", (DL_FUNC) &_bbssr_max_tail_prob_refined, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_bbssr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
