// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// max_tail_prob
NumericVector max_tail_prob(NumericMatrix dbinom1, NumericMatrix dbinom2, IntegerVector x1, IntegerVector x2, IntegerVector idx_last, IntegerVector g_lo, IntegerVector g_hi);
RcppExport SEXP _bbssr_max_tail_prob(SEXP dbinom1SEXP, SEXP dbinom2SEXP, SEXP x1SEXP, SEXP x2SEXP, SEXP idx_lastSEXP, SEXP g_loSEXP, SEXP g_hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dbinom1(dbinom1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dbinom2(dbinom2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx_last(idx_lastSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g_lo(g_loSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g_hi(g_hiSEXP);
    rcpp_result_gen = Rcpp::wrap(max_tail_prob(dbinom1, dbinom2, x1, x2, idx_last, g_lo, g_hi));
    return rcpp_result_gen;
END_RCPP
}
// power_from_rr
double power_from_rr(LogicalMatrix RR, NumericVector dbinom1, NumericVector dbinom2);
RcppExport SEXP _bbssr_power_from_rr(SEXP RRSEXP, SEXP dbinom1SEXP, SEXP dbinom2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dbinom1(dbinom1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dbinom2(dbinom2SEXP);
    rcpp_result_gen = Rcpp::wrap(power_from_rr(RR, dbinom1, dbinom2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bbssr_max_tail_prob", (DL_FUNC) &_bbssr_max_tail_prob, 7},
    {"_bbssr_power_from_rr", (DL_FUNC) &_bbssr_power_from_rr, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_bbssr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
