# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_tail_prob <- function(dbinom1, dbinom2, x1, x2, idx_last, g_lo, g_hi) {
    .Call(`_bbssr_max_tail_prob`, dbinom1, dbinom2, x1, x2, idx_last, g_lo, g_hi)
}

power_from_rr <- function(RR, dbinom1, dbinom2) {
    .Call(`_bbssr_power_from_rr`, RR, dbinom1, dbinom2)
}

